=== ym-team/code-generate-tool/schema/database.dtd
<?xml version="1.0" encoding="gb2312"?>
<!ELEMENT app-data (database+)>
<!ELEMENT database (module+)>
<!ATTLIST database
	name CDATA #IMPLIED
	defaultIdMethod (native | none) "none"
	package CDATA #IMPLIED
	baseClass CDATA #IMPLIED
	basePeer CDATA #IMPLIED
	defaultNameConversion (nochange | underscore | javaname) "underscore"
>
<!ELEMENT module (submodule*)>
<!ATTLIST module
	name CDATA #IMPLIED
	chineseDescription CDATA #IMPLIED
>
<!ELEMENT submodule (table+)>
<!ATTLIST submodule
	name CDATA #IMPLIED
	chineseDescription CDATA #IMPLIED
>
<!ELEMENT table ( rem*,column+, ( foreign-key | index | unique | id-method-parameter | family)*)>
<!ATTLIST table
	name CDATA #REQUIRED
	javaName CDATA #IMPLIED
	idMethod (native | none | null) "null"
	baseClass CDATA #IMPLIED
	alias CDATA #IMPLIED
	nameConversion (nochange | underscore | javaname) #IMPLIED
	pkg CDATA #IMPLIED
	jspPath CDATA #IMPLIED
	chineseDescription CDATA #IMPLIED
	uuid CDATA #IMPLIED
	pageLines CDATA #IMPLIED
	function1 CDATA #IMPLIED
	onHelp (true|false) "false"
	simple (true|false) "false"
	head CDATA #IMPLIED
	line CDATA #IMPLIED
>
<!ELEMENT rem (#PCDATA)>
<!ELEMENT column EMPTY>
<!ATTLIST column
	name CDATA #REQUIRED
	javaName CDATA #IMPLIED
	primaryKey (true | false) "false"
	autoIncrement (true | false) "false"
	required (true | false) "false"
	type
	  (
			  BIT  | TINYINT | SMALLINT    | INTEGER    | BIGINT    | FLOAT
			| REAL | NUMERIC | DECIMAL     | CHAR       | VARCHAR   | LONGVARCHAR
			| DATE | TIME    | TIMESTAMP   | BINARY     | VARBINARY | LONGVARBINARY
			| NULL | OTHER   | JAVA_OBJECT | DISTINCT   | STRUCT    | ARRAY
			| BLOB | CLOB    | REF         | BOOLEANINT | BOOLEANCHAR
			| DOUBLE
	   ) "VARCHAR"
	size CDATA #IMPLIED
	default CDATA #IMPLIED
	inputValidator CDATA #IMPLIED
	nameConversion (nochange | underscore | javaname) #IMPLIED
	chineseDescription CDATA #IMPLIED
	pkg CDATA #IMPLIED
	isGet (true | false) "false"
	enumValue CDATA #IMPLIED
	order (true | false) "false"
	orderMethod (ASC | DESC) "ASC"
	inSelect (true | false) "true"
	searchShow (true | false) "true"
	insertShow (true | false) "true"
	updateShow (true | false) "true"
	queryShow (true | false) "true"
	detailShow (true | false) "true"
	format (money | amount | date | time) #IMPLIED
	inputSize CDATA #IMPLIED
	readOnlyU (true | false) "false"
	readOnlyI (true | false) "false"	
	note CDATA #IMPLIED
>
<!ELEMENT foreign-key (reference+)>
<!ATTLIST foreign-key
	foreignTable CDATA #REQUIRED
	name CDATA #IMPLIED
	onUpdate (help | select | hidden | text | none) "none"
	onInsert (help | select | hidden | text | none) "none"
	showCol CDATA #IMPLIED
	noSql (true | false) "false"
	typeCol CDATA #IMPLIED
	typeValue CDATA #IMPLIED
>
<!ELEMENT reference EMPTY>
<!ATTLIST reference
	local CDATA #REQUIRED
	foreign CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!ELEMENT index (index-column+)>
<!ATTLIST index
	name CDATA #IMPLIED
>
<!ELEMENT index-column EMPTY>
<!ATTLIST index-column
	name CDATA #REQUIRED
	size CDATA #IMPLIED
>
<!ELEMENT unique (unique-column+)>
<!ATTLIST unique
	name CDATA #IMPLIED
>
<!ELEMENT unique-column EMPTY>
<!ATTLIST unique-column
	name CDATA #REQUIRED
>
<!ELEMENT id-method-parameter EMPTY>
<!ATTLIST id-method-parameter
	name CDATA "default"
	value CDATA #REQUIRED
>
<!ELEMENT family EMPTY>
<!ATTLIST family
	childTable CDATA #REQUIRED
	childLocal CDATA #REQUIRED
	parentLocal CDATA #REQUIRED
	childForeign CDATA #REQUIRED
	parentForeign CDATA #REQUIRED
>
<!--
1.table的family单元用于描述这个表中某些列之间的“亲属”关系，如slsman是儿子child，node是父亲parent
	在childTable中childForeign必须是主键,parentForeign必须在childTable中有定义
2.foreign-key有4种：
	1) 一般的
	noSql="false"，会生成数据库表的外键
	2) 虚拟的
	noSql="true"
	在foreign-key中有一个noSql属性，表示这个外键是否需要在数据库中建立，如果noSql=false，表示
	这个外键是一个“虚拟”的外键，只是为了描述数据之间的逻辑关系，同时为了生成程序，如下拉框用。
	3)虚拟并一对多表的
	noSql="true" typeCol/typeValue有定义
	用于表示表中的一个列对应多个表的情况，如在仓库事务matltrans中ref_type/ref_num/ref_line字段
	4)虚拟并多对一表的
	noSql="true" 在reference中local="" value有定义
	如损溢单PROFIT_LOSS中的原因码REASON
4.
-->

=== ym-team/code-generate-tool/schema/FAQ_info.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="PUBLIC_SCHEMA.xsl"?>
<!DOCTYPE app-data SYSTEM "database.dtd">
<app-data>
	<database>	
	<!--问题反馈记录信息维护-->
		<module name="FAQ" chineseDescription="系统菜单">
			<submodule name="FAQ_INFORMATION" chineseDescription="系统菜单">                  
				<table name="SYS_PT_MENU" chineseDescription="系统菜单" pkg="syscode" jspPath="platform/FAQ/info">
					<rem> ==================================================================== </rem>
					<rem> 问题反馈记录信息维护							                                   </rem>
					<rem> 输入人:        输入日期:2006.06.02	  			               </rem>					
					<rem> 修改人:                 修改日期:                                       </rem>
					<rem> 修改变动:                                                              </rem>
					<rem> ==================================================================== </rem>
					<column name="MENU_ID" primaryKey="true" required="true" type="VARCHAR" size="36" chineseDescription="菜单内码" queryShow="true"/>
					<column name="MENU_TREE_CODE" required="true" type="VARCHAR" size="200"  chineseDescription="菜单编码" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>
					<column name="MENU_NAME" primaryKey="true" required="true" type="VARCHAR" size="36" chineseDescription="菜单名称" queryShow="true"/>
				</table>					   
			</submodule>			
		</module>		
	</database>
</app-data>

=== ym-team/code-generate-tool/schema/DATA_RES.xml
<?xml version="1.0" encoding="gb2312" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="PUBLIC_SCHEMA.xsl"?>
<!DOCTYPE app-data SYSTEM "database.dtd">
<app-data>
	<database>	
	<!--数据权限-->
		<module name="PF_DATA_RES" chineseDescription="数据权限">
			<submodule name="PF_DATA_RES" chineseDescription="数据权限">                  
				<table name="PF_DATA_RES" chineseDescription="数据权限类型" pkg="dataRes.define" jspPath="dataRes/define">
					<rem> ==================================================================== </rem>
					<rem> 指标代码表	JT_ITEM_CODE						                                   </rem>
					<rem> 输入人: ZDVT      输入日期:2006.06.02	  			               </rem>					
					<rem> 修改人:                 修改日期:                                       </rem>
					<rem> 修改变动:                                                              </rem>
					<rem> ==================================================================== </rem>
					<column name="ID" primaryKey="true" required="true" type="VARCHAR" size="30" chineseDescription="类型编号" queryShow="true"  updateShow="true" insertShow="true" detailShow="true"/>
					<column name="NAME" required="true" type="VARCHAR" size="100"  chineseDescription="类型名称" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>
					<column name="FILTER_KEY" required="true" type="VARCHAR" size="50"  chineseDescription="过滤的关键字段" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>					
					<column name="FILTER_KEY_NOTE" required="false" type="VARCHAR" size="100"  chineseDescription="关键字段说明" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>										
					<column name="FILTER_NAME" required="true" type="VARCHAR" size="50" chineseDescription="关键字显示信息字段"  queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>										
					<column name="FILTER_NAME_NOTE" required="false" type="VARCHAR" size="100" chineseDescription="显示字段说明" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>														
					<column name="FILTER_SQL" required="true" type="VARCHAR" size="1000" chineseDescription="过滤条件(SQL)"    queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>										
					<column name="DEFAULT_KEY" required="false" type="VARCHAR" size="300" chineseDescription="默认关键字" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>															
					<column name="NOTE" required="false" type="VARCHAR" size="300" chineseDescription="备注" queryShow="false" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>															
					<column name="NOTE2" required="false" type="VARCHAR" size="100" chineseDescription="NOTE2" queryShow="false" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>															
					<column name="NOTE3" required="false" type="VARCHAR" size="100" chineseDescription="NOTE3" queryShow="false" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>															

					<index name="INX_DATA_RES_NAME">
			        	<index-column name="NAME"/>
			        </index>
				</table>				
				
				<table name="PF_DATA_RES_LIST" chineseDescription="用户数据权限列表" pkg="dataRes.list" jspPath="dataRes/list">
					<rem> ==================================================================== </rem>
					<rem> 指标代码表	MP_MESSAG						                                   </rem>
					<rem> 输入人: ZDVT      输入日期:2006.06.02	  			               </rem>					
					<rem> 修改人:                 修改日期:                                       </rem>
					<rem> 修改变动:                                                              </rem>
					<rem> ==================================================================== </rem>
					<column name="ID" primaryKey="true" required="true" type="VARCHAR" size="36" chineseDescription="主键" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>
					<column name="USER_ID" required="true" type="VARCHAR" size="30" chineseDescription="用户编号" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>
					<column name="DATA_RES_ID" required="true" type="VARCHAR" size="30"  chineseDescription="数据权限类型" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>
					<column name="FILTER_KEY"  required="true" type="VARCHAR" size="100"  chineseDescription="过滤关键字" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>					
					<column name="FILTER_NAME" required="true" type="VARCHAR" size="200"  chineseDescription="关键字显示信息" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>										
					<column name="NOTE" required="false" type="VARCHAR" size="300" chineseDescription="备注" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>															
					<column name="NOTE2" required="false" type="VARCHAR" size="100" chineseDescription="NOTE2" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>															
					<column name="NOTE3" required="false" type="VARCHAR" size="100" chineseDescription="NOTE3" queryShow="true" searchShow="true" updateShow="true" insertShow="true" detailShow="true"/>															
					<foreign-key foreignTable="PF_DATA_RES">
				    	<reference local="DATA_RES_ID" foreign="ID"/>
			        </foreign-key>			       
			       	<foreign-key foreignTable="PF_USER_DEPT">
				    	<reference local="USER_ID" foreign="USERID"/>
			        </foreign-key> 
			        <unique name="UK_PF_DATA_RES_LIST" >
			        	<unique-column name="USER_ID"/>
			        	<unique-column name="DATA_RES_ID"/>
			        	<unique-column name="FILTER_KEY"/>
			        </unique>
				</table>				
			</submodule>
			
		</module>		
	</database>
</app-data>

=== ym-team/code-generate-tool/schema/test.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="PUBLIC_SCHEMA.xsl"?>
<!DOCTYPE app-data SYSTEM "database.dtd">
<app-data>
	<database>	
	<!--平台系统定义-->
		<module name="SYS" chineseDescription="平台系统定义">
			<submodule name="SYS_PT_SYSTEM" chineseDescription="平台系统定义">  
			                
<table name='t_social_keyword' chineseDescription='敏感词' pkg='social' jspPath='platform/permit/userRole' >
<column name='id'   primaryKey='true' required='true' type='INTEGER'  chineseDescription=''/>
<column name='content'   primaryKey='true' required='true' type='VARCHAR'  chineseDescription='内容'/>
<column name='status'   primaryKey='true' required='true' type='INTEGER'  chineseDescription='0-停用 1-启用'/>
<column name='mark'   primaryKey='true' required='true' type='VARCHAR'  chineseDescription='备注'/>
<column name='create_time'   primaryKey='true' required='true' type='BIGINT'  chineseDescription='创建时间'/>
<column name='modify_time'   primaryKey='true' required='true' type='BIGINT'  chineseDescription='最后修改时间'/>
</table>
			</submodule>			
		</module>		
	</database>
</app-data>
